server.port=8083
server.servlet.context-path=/Projeto_x

spring.datasource.url=jdbc:mysql://pontelli.net.br:3306/pontelli93b45689_italo09db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Sao_Paulo
spring.datasource.username=
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
